### ISSUE TITLE
Sorting by time does not behave as expected

### ISSUE THREAD

**Issue by lillian27** [whoishiring/feedback#1]
Sorting by time only works if there are no other filters.  If you add additional filters (text search=Python for example) then results are not sorted by time over the set, but seem to be sorted by time in clusters.  

Continuing this example, if you now change to sorting by distance the ordering of the results does not change.  This suggests that sorting by time is being ignored when other filters are present.

This used to work before some of the new filtering options were added.

I should be able to add as many filters as are available and have the returned results be sorted by time over the whole result set.

**Comment by xando** [comment]
Hey @lillian27 thanks for the report. The fix was deployed.
