### ISSUE TITLE
Mismatch on Remote tag

### ISSUE THREAD

**Issue by koblas** [whoishiring/feedback#10]
This post -- 

Superhuman - https://superhuman.com | Fullstack Engineer & iOS Engineer | Founding Team | Full-time | San Francisco | ONSITE

Why?  In the description there is the lines -- note the "remote" in the interview section.

• Culture: coffee/phone call [1 hr]
• Tech: onsite/remote coding project + interview [2 hrs]
• Tech: coding project [multiple days, paid]

**Comment by xando** [comment]
Hey, @koblas Thanks for the report.

The item is updated. https://whoishiring.io/search/45.164/-101.030/1/#hn12207035
