### ISSUE TITLE
NOT operator not excluding results

### ISSUE THREAD

**Issue by ZugboTheCerebral** [whoishiring/feedback#11]
Searching for `NOT Designer` returns jobs with designer in both the title and description. Searching for `NOT "Designer"` has the same results. Searching for `"NOT Designer"` returns nothing. 

Expected behavior is a list of postings, none of which contain the word "Designer".

**Comment by xando** [comment]
Hey @ZugboTheCerebral thanks for report we are looking at this issue.

**Comment by jeffisabelle** [comment]
Hi, I saw a similar problem, didn't want to create a new issue. 

AND operator doesn't seem to work, 
`python AND aws` currently shows 11839 results, `python AND asdfasdfasdf` shows 11839 results as well.

**Comment by xando** [comment]
I've just deployed the fix for the issue. 

@ZugboTheCerebral @jeffisabelle thanks for the feedback.
