### ISSUE TITLE
Date is different

### ISSUE THREAD

**Issue by username1290** [whoishiring/feedback#15]
Date in whoishiring.io is different from the posted date:

Whoishiring date: October 23
![screen shot 2016-10-23 at 12 54 02 pm](https://cloud.githubusercontent.com/assets/2784323/19628278/d7f0d548-991f-11e6-9b0c-3f08be4a6e9b.png)

visit the listing, it says posted date **September 7**
![screen shot 2016-10-23 at 12 56 49 pm](https://cloud.githubusercontent.com/assets/2784323/19628292/2d5bdfaa-9920-11e6-8e8c-fceb9f29b94d.png)

**Comment by xando** [comment]
Thanks! and fixed!
