### ISSUE TITLE
Total number of results doesn't update

### ISSUE THREAD

**Issue by jadedevin13** [whoishiring/feedback#19]
If you search for node. This will be the total number of results.

![image](https://cloud.githubusercontent.com/assets/6671182/20651398/b2ad13f2-b51f-11e6-8227-72644d8fc24f.png)

If you search for java without refreshing the page, this will be the total number of results.
![image](https://cloud.githubusercontent.com/assets/6671182/20651404/c6cc0a28-b51f-11e6-882e-382ecfc990ba.png)

If you refresh the page and search for java with the same map location view. Here is the result.

![image](https://cloud.githubusercontent.com/assets/6671182/20651410/f800b350-b51f-11e6-8027-09524920b4b7.png)

**Comment by xando** [comment]
hey @jadedevin13 

thanks for the report. The fix was commited and deployed. 

Thanks
