### ISSUE TITLE
how do you do your marker clustering?

### ISSUE THREAD

**Issue by blairanderson** [whoishiring/feedback#21]
i think its super neat, would love to see how you got that to work?

**Comment by imjared** [comment]
@blairanderson here's a link for how to do it in Google maps: https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by blairanderson** [comment]
Ohhhh. well your icons look way better than the demo 👍

**Comment by xando** [comment]
The clustering is done in very different way from the link that @imjared provided. It's custom solution that helps me with rendering many objects on the map. Those object are not Google API objects. 

Said that. If your map is less 100 object you will be fine with link that @imjared provided. You can add custom icons there as well.

**Comment by blairanderson** [comment]
I have 2000 objects that are being clustered and the performance is slow.  

Do you have a reference for how you handled clustering?
