### ISSUE TITLE
Stricter location parsing?

### ISSUE THREAD

**Issue by imjared** [whoishiring/feedback#22]
Richmond, UK !== Richmond, VA

![image](https://cloud.githubusercontent.com/assets/525011/20821049/8ff34a20-b80d-11e6-91e4-9d852916ef5c.png)

**Comment by xando** [comment]
Thanks @imjared 

The parsing seems to be fine the geo geolocation answers seems to be a bit controversial.  US locations always have priority i happened for Melbourne before. 

Will look at it.
