### ISSUE TITLE
Option to "report" a posting

### ISSUE THREAD

**Issue by BlackVegetable** [whoishiring/feedback#32]
This is a feature request.  Supposing you have resources to follow up on such, perhaps a button to click to allow users to select from a few different messages as to why a posting is incorrect (or possibly offensive/spam) would be nice.  I've seen a few options parsed as "Remote" that don't seem to be remote positions.  I'm thinking of something with the UX/UI of the Stack Exchange Network's "Close Vote" reason selection:

![close](https://cloud.githubusercontent.com/assets/2665839/22435083/ddd88b18-e6db-11e6-9e16-1135f5eb5103.JPG)

**Comment by xando** [comment]
Hey @BlackVegetable this sound very reasonable. And actually some time in the past whoishiring was equipped with similar function. I will try to revert back this functionality;

**Comment by BlackVegetable** [comment]
Neat! Supposing you have the man/woman-hours to spend going through reports, it could improve the quality of the postings, and/or the parsing algorithm.

**Comment by xando** [comment]
@BlackVegetable 

I've just implemented basic report form. Look for "! report" button

**Comment by BlackVegetable** [comment]
Neat! Thanks.
