### ISSUE TITLE
Needs Authentication

### ISSUE THREAD

**Issue by himanshugarg** [whoishiring/feedback#34]
I see a password prompt everytime I connect to the site from my home network. I am not a robot.

**Comment by xando** [comment]
Hey,

Thanks for the report.

I'm guessing it is Cloudflare's captcha. In this case please have a look
here
https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-

If it's something else, please attach a screenshot here.

**Comment by himanshugarg** [comment]
AFAICT it looked like a basic auth dialog but will share screenshot anyway. Thanks for looking at this.

**Comment by xando** [comment]
Ok thanks. 

If you can, please attach javascript console as well and current URL.

**Comment by himanshugarg** [comment]
![image](https://cloud.githubusercontent.com/assets/2392803/23690410/7c00830e-03e7-11e7-9673-656b92ae8b36.png)

**Comment by himanshugarg** [comment]
Not seeing this today.

**Comment by xando** [comment]
It looks like one of our servers (in rotation) had a bad nginx conf. This should be fixed. Thanks for the report
