### ISSUE TITLE
Showing Mountain View postings in Martinez

### ISSUE THREAD

**Issue by kuwood** [whoishiring/feedback#39]
Some postings for mountain view are showing up in martinez.

### Screenshot of issue
![mountain_view_not_martinez](https://cloud.githubusercontent.com/assets/6320220/25629216/a398fef8-2f1d-11e7-85f6-f21f3e35d0cd.png)

**Comment by xando** [comment]
hey @kuwood thanks for taking time to submit this issue!

It should be fixed!
