### ISSUE TITLE
JSON API would be cool.

### ISSUE THREAD

**Issue by ghost** [whoishiring/feedback#42]
I am writing my own aggregator of job listing sites, and it'd be helpful if WhoIsHiring had a JSON API. In the meantime I plan on using Selenium to scrape the results.

**Comment by xando** [comment]
I got this a lot, I don't have resources to do it or a good motivation. It one man project, building and API would take a lot of my time. 

Do you mind sharing the idea? What you are going do with the data?

**Comment by ghost** [comment]
Im a programmicrastinator. I procrastinate applying to jobs by doing hobby
projects. This particular project is a Ruby REPL for facilitating the job
application process. Dont worry about it.
