### ISSUE TITLE
Mozilla job incorrectly shown as being "Mozilla Türkiye"

### ISSUE THREAD

**Issue by heycam** [whoishiring/feedback#47]
In the listing at https://whoishiring.io/search/25.0338/121.5630/8?search=Mozilla the entry for the Sr. Front-end Engineer says "Mozilla Türkiye".  I'm not sure where it gets that from but it should be "Mozilla" or maybe "Mozilla Taiwan".

**Comment by xando** [comment]
It looks like a data error on Mozilla's side. And it's not longer an issue
