### ISSUE TITLE
Data Issue

### ISSUE THREAD

**Issue by dev4all** [whoishiring/feedback#50]
Unable to see the job postings. The data in each of the posts does not appear. The country names, Job Titles, Descriptions, etc.

**Comment by xando** [comment]
Hey thanks for the report what is the browser, os and country that you are trying to connect from?

**Comment by dev4all** [comment]
I have tried on Windows 7, Chrome and also on a dual boot Windows 7 sitting on a macbook using Chrome, IE and Opera

**Comment by xando** [comment]
Thanks, and what is what is your country? I have few search servers I'm trying to figure to which your are connected to. 

Could you attach screenshot as well?

**Comment by dev4all** [comment]
I am in Canada. I just tried on Mac OS Sierra 10.12.6 and it working on Chrome. btw is it possible to work on this project on spare time...

**Comment by dev4all** [comment]
Mac OS seems fine on Firefox. Not working on Windows 7 firefox either.

**Comment by dev4all** [comment]
<img width="1440" alt="win7_chrome" src="https://user-images.githubusercontent.com/1689395/29356310-d92daaa6-8241-11e7-824a-5a9cd4dfaf4e.png">
![Uploading win7_firefox.png…]()

**Comment by dev4all** [comment]
first one is chrome, second is firefox on Windows 7 from Canada

**Comment by dev4all** [comment]
<img width="1440" alt="win7_firefox" src="https://user-images.githubusercontent.com/1689395/29382740-9a34519c-829b-11e7-8be0-550bce14b378.png">

**Comment by dev4all** [comment]
firefox ^

**Comment by xando** [comment]
Hey for the help here and for the screenshots.

For sure something is going wrong way there. I've just checked on Windows
10 machine, on most recent Chorme, FF and Edge. It looks fine.

Having said that, do you know how to make a screen shot with JS console
logs? This would be really useful.

**Comment by dev4all** [comment]
It just started working again!!

**Comment by xando** [comment]
I haven't done much really. let's call it magic then :) 

Thanks again
