### ISSUE TITLE
All result sorting is broken/being ignored

### ISSUE THREAD

**Issue by lillian27** [whoishiring/feedback#55]
Sorting results by relevant/location/time is broken; all choices show the same order of results.  No keywords or additional filters needed, just:

1) Go to main page https://whoishiring.io/
2) click "Search"
3) On results page change "Sort by relevance" to "Sort by location".  No change.
4) Change from location to time.  No change.

Changing the "Created" filter does scope the results, but sorting within those results is still incorrect or being ignored.

**Comment by xando** [comment]
fixed
