### ISSUE TITLE
Broken JavaScript and/or reliance on bleeding-edge browser support.

### ISSUE THREAD

**Issue by ghost** [whoishiring/feedback#56]
whoishiring.io effectively stopped working for me about a week ago, in that I can see the home page, but an attempt to search gives me no results. This corresponded to a change in appearance but whether that change was an intended design change or related to this bug, I couldn't say. The JavaScript console gives this error whenever I attempt a search:
```
Unhandled promise rejection Error: Request failed with status code 400
Stack trace:
e.exports@https://whoishiring.io/0f6ff60c7ad5e410d693vendor.js:25:318022
e.exports@https://whoishiring.io/0f6ff60c7ad5e410d693vendor.js:47:1220
e.exports/</p[h]@https://whoishiring.io/0f6ff60c7ad5e410d693vendor.js:25:317036
r@https://whoishiring.io/0f6ff60c7ad5e410d693vendor.js:62:362707
```
I have tested using Firefox 41.0.1 and Safari 9.1.3 on MacOS 10.9.5, and suspect the problem is that you're using features only supported by newer versions. At this time, I am not interested in upgrading my browser or OS (which would be required to get a newer Safari) since this would break as much as it fixes.

**Comment by xando** [comment]
Hey @mooli your guess here is pretty much correct, I've started using css grids. And those are related to the map rendering and this to search and building query from the map. 

It looked as reasonable thing to do https://caniuse.com/#feat=css-grid. 

I might fight for some backward compatibility in future but maintaining sanity css files is extremely hard thing to achieve, even with new features. Not sure if it's worth it at this point. And even if I'll do it you will get mobile version for old browsers.
