### ISSUE TITLE
Text search returning results for each word, not whole string. 

### ISSUE THREAD

**Issue by iamyashrs** [whoishiring/feedback#7]
Ex: I searched for "google app engine" but got results for "google", "app" and "engine".

**Comment by moubarak** [comment]
Same here. "computer vision" returns all results for "computer" and all results for "vision".

**Comment by xando** [comment]
Thanks for the reports.
This one is fixed and deployed.

**Comment by HenningJ** [comment]
This issue seems to have reappeared :(

**Comment by HenningJ** [comment]
Again: this issue seems to have reappeared. Searching for "computer vision" returns all results for "computer" and all results for "vision". That makes the search basically useless for me. :-(

**Comment by vonneudeck** [comment]
Unfortunately the regression is still there @xando .
