### ISSUE TITLE
Allow search for contract jobs

### ISSUE THREAD

**Issue by canni** [whoishiring/feedback#8]
Currently AFAIK the only option for searching a contract ads is through text search, and IMO job type `permanent|contract|any` should be exposed as a clear filter, like visa or remote options, no?

**Comment by xando** [comment]
I agree we should do something about it. Most of the sources we have are just permanent, though. 

@canni can you recommend a good source for contract jobs.

We definitely could add a job type in our add job form.

**Comment by canni** [comment]
Unfortunately I don't know any source which wouldn't already be a job posting directory.
But as a work-around the contract filter could be just an alias for text search concatenated with `AND` op.
Most ads that are allowing contracts are explicit with mentioning it

**Comment by xando** [comment]
Hey @canni this was implemented. Look for more filters option
